jax:
  url: https://github.com/google/jax.git
  tracking_ref: main
  latest_verified_commit: 51719a1afe559d0e2b44120dcf21076831b0704f
  mode: git-clone
xla:
  url: https://github.com/openxla/xla.git
  tracking_ref: main
  latest_verified_commit: e0e56a1190d5be336f7d3e308457349fbfacebd2
  mode: git-clone
flax:
  url: https://github.com/google/flax.git
  mirror_url: https://github.com/nvjax-svc-0/flax.git
  tracking_ref: main
  latest_verified_commit: 0769411f7b11e3024d1b16c5eaaab95eb6670383
  mode: git-clone
  patches:
    pull/3340/head: file://patches/flax/PR-3340.patch # Add Sharding Annotations to Flax Modules
transformer-engine:
  url: https://github.com/NVIDIA/TransformerEngine.git
  tracking_ref: main
  latest_verified_commit: f8eddcf9278416815c286aac74cbbba96bf66ad3
  mode: git-clone
t5x:
  url: https://github.com/google-research/t5x.git
  mirror_url: https://github.com/nvjax-svc-0/t5x.git
  tracking_ref: main
  latest_verified_commit: ad6a629aa61f7353998482055feee597b651093f
  mode: git-clone
  patches:
    mirror/patch/partial-checkpoint-restore: file://patches/t5x/mirror-patch-partial-checkpoint-restore.patch # pull/1392/head  # https://github.com/google-research/t5x/pull/1392: Add support for partial checkpoint restore
    mirror/patch/dali-support: file://patches/t5x/mirror-patch-dali-support.patch # pull/1393/head  # https://github.com/google-research/t5x/pull/1393: Adds DALI support to t5x
    mirror/patch/t5x_te_in_contrib_noindent: file://patches/t5x/mirror-patch-t5x_te_in_contrib_noindent.patch # pull/1391/head  # https://github.com/google-research/t5x/pull/1391: Adds transformer engine support and GPU optimizations to T5x (enables H100)
paxml:
  url: https://github.com/google/paxml.git
  mirror_url: https://github.com/nvjax-svc-0/paxml.git
  tracking_ref: main
  latest_verified_commit: 37d5f0ec5768f92574b00dc53169ed267fe465cb
  mode: git-clone
  patches:
    pull/46/head: file://patches/paxml/PR-46.patch # adds Transformer Engine support
    pull/93/head: file://patches/paxml/PR-93.patch # exposes TE DPA argument in Grok to make it configurable from the command line
praxis:
  url: https://github.com/google/praxis.git
  mirror_url: https://github.com/nvjax-svc-0/praxis.git
  tracking_ref: main
  latest_verified_commit: 45d668258d9a2dce7b326688b7096ad966f3e10c
  mode: git-clone
  patches:
    pull/27/head: file://patches/praxis/PR-27.patch # This PR allows XLA:GPU to detect the MHA pattern more easily to call fused kernels from cublas.
    pull/36/head: file://patches/praxis/PR-36.patch # adds Transformer Engine support
    pull/84/head: file://patches/praxis/PR-84.patch # experimental support for using TE FMHA in GQA
lingvo:
  # Used only in ARM pax builds
  url: https://github.com/tensorflow/lingvo.git
  tracking_ref: master
  latest_verified_commit: 03fd809d63f852816912cbf28ee299f6a47dbd0b
  mode: git-clone
tensorflow-text:
  # Used only in ARM pax and t5x builds
  url: https://github.com/tensorflow/text.git
  tracking_ref: v2.13.0
  latest_verified_commit: 917a681d7220ebf9b62a08b6f9ce7b7db886ddef
  mode: git-clone
pydantic:
  version: X.Y.Z
  mode: pip-constraint
# Used by praxis
fiddle:
  url: https://github.com/google/fiddle.git
  tracking_ref: main
  latest_verified_commit: d45d7cae1a2d117deb8ee9c2f34e4ba7820d34f0
  mode: pip-vcs
# Used by t5x
airio:
  url: https://github.com/google/airio.git
  tracking_ref: main
  latest_verified_commit: c6531b3653c7453bcc0bcb5ae241f1191be1ae51
  mode: pip-vcs
clu:
  url: https://github.com/google/CommonLoopUtils.git
  tracking_ref: main
  latest_verified_commit: a8152eb825dc04df8acdbb2b42fc89f9aafa37ba
  mode: pip-vcs
dllogger:
  url: https://github.com/NVIDIA/dllogger.git
  tracking_ref: master
  latest_verified_commit: 0540a43971f4a8a16693a9de9de73c1072020769
  mode: pip-vcs
jestimator:
  url: https://github.com/google-research/jestimator.git
  tracking_ref: main
  latest_verified_commit: 326824a477feef6d92e6f44175000907a72899ca
  mode: pip-vcs
optax:
  url: https://github.com/google-deepmind/optax.git
  tracking_ref: main
  latest_verified_commit: 76cbf5f3a9463eda8432dd86f18a1e3495ad5a40
  mode: pip-vcs
seqio:
  url: https://github.com/google/seqio.git
  tracking_ref: main
  latest_verified_commit: bb079d8b7f98802793c8a2b314114caabf83bab1
  mode: pip-vcs
jax-triton:
  url: https://github.com/jax-ml/jax-triton.git
  tracking_ref: main
  latest_verified_commit: 150af1f758acf028a7bd64dbaba45df8f711212c
  mode: git-clone
maxtext:
  url: https://github.com/google/maxtext.git
  tracking_ref: main
  latest_verified_commit: 4797997fcd08ac287f26c099ede9ae6c2bce77e4
  mode: git-clone
levanter:
  url: https://github.com/stanford-crfm/levanter.git
  tracking_ref: main
  latest_verified_commit: e63a1ebc3bde165fbb37da2d8a059d42d7ad2733
  mode: git-clone
haliax:
  url: https://github.com/stanford-crfm/haliax.git
  tracking_ref: main
  latest_verified_commit: f8a5ade62c0177911683937f7d57e8e876518515
  mode: git-clone
mujoco:
  url: https://github.com/google-deepmind/mujoco.git
  tracking_ref: main
  latest_verified_commit: 0f563ecf31bf178424fda4eb320e83c1de4f0cf7
  mode: git-clone
mujoco-mpc:
  url: https://github.com/google-deepmind/mujoco_mpc.git
  tracking_ref: main
  latest_verified_commit: 9bd2037498056a0ab9cf9463ab841e40fef54142
  mode: git-clone
language-to-reward-2023:
  url: https://github.com/google-deepmind/language_to_reward_2023.git
  tracking_ref: main
  latest_verified_commit: 4a3a20f9c8705e3a3ded4d218d9c129303d9682e
  mode: git-clone
mlperf-logging:
  url: https://github.com/mlcommons/logging.git
  tracking_ref: master
  latest_verified_commit: d3174f21d14c2026063a43e38fac41de4e4df200
  mode: pip-vcs
gemma:
  url: https://github.com/google-deepmind/gemma.git
  tracking_ref: main
  latest_verified_commit: 6454fc7b0871c932a0fb5e6b3163a4653f32ddd3
  mode: git-clone
equinox:
  url: https://github.com/patrick-kidger/equinox.git
  tracking_ref: main
  latest_verified_commit: 8191b113df5d985720e86c0d6292bceb711cbe94
  mode: git-clone
big-vision:
  url: https://github.com/google-research/big_vision.git
  tracking_ref: main
  latest_verified_commit: 332565368df27457f47ace494a99dcd3748d5207
  mode: git-clone
common-loop-utils:
  url: https://github.com/google/CommonLoopUtils.git
  tracking_ref: main
  latest_verified_commit: a8152eb825dc04df8acdbb2b42fc89f9aafa37ba
  mode: git-clone
flaxformer:
  url: https://github.com/google/flaxformer.git
  tracking_ref: main
  latest_verified_commit: 399ea3a85e9807ada653fd0de1a9de627eb0acde
  mode: git-clone
panopticapi:
  url: https://github.com/akolesnikoff/panopticapi.git
  tracking_ref: mute
  latest_verified_commit: a698a12deb21e4cf0f99ef0581b2c30c466bf355
  mode: git-clone
orbax-checkpoint:
  url: https://github.com/google/orbax.git
  tracking_ref: main
  latest_verified_commit: d010cfa96c08dc546bce7c10e8e959214e76e077
  mode: pip-vcs
pathwaysutils:
  url: https://github.com/google/pathways-utils.git
  tracking_ref: main
  latest_verified_commit: 65d8a4f20740ecf6259037b1d8ebc812a66d47c3
  mode: pip-vcs
