jax:
  url: https://github.com/google/jax.git
  tracking_ref: main
  latest_verified_commit: b510127a13e769e9b1cc334c09be3bc2b9ad6700
  mode: git-clone
xla:
  url: https://github.com/openxla/xla.git
  tracking_ref: main
  latest_verified_commit: 1cb031a84db96167e22972b90c38b9df178bcc1a
  mode: git-clone
flax:
  url: https://github.com/google/flax.git
  mirror_url: https://github.com/nvjax-svc-0/flax.git
  tracking_ref: main
  latest_verified_commit: 1ec5ef29777b13c0cfd3f6bad37a72153a45291c
  mode: git-clone
  patches:
    pull/3340/head: file://patches/flax/PR-3340.patch # Add Sharding Annotations to Flax Modules
transformer-engine:
  url: https://github.com/NVIDIA/TransformerEngine.git
  tracking_ref: main
  latest_verified_commit: 257345a56d006bb24be890bfd813b1d1299807a8
  mode: git-clone
t5x:
  url: https://github.com/google-research/t5x.git
  mirror_url: https://github.com/nvjax-svc-0/t5x.git
  tracking_ref: main
  latest_verified_commit: ad6a629aa61f7353998482055feee597b651093f
  mode: git-clone
  patches:
    mirror/patch/partial-checkpoint-restore: file://patches/t5x/mirror-patch-partial-checkpoint-restore.patch # pull/1392/head  # https://github.com/google-research/t5x/pull/1392: Add support for partial checkpoint restore
    mirror/patch/dali-support: file://patches/t5x/mirror-patch-dali-support.patch # pull/1393/head  # https://github.com/google-research/t5x/pull/1393: Adds DALI support to t5x
    mirror/patch/t5x_te_in_contrib_noindent: file://patches/t5x/mirror-patch-t5x_te_in_contrib_noindent.patch # pull/1391/head  # https://github.com/google-research/t5x/pull/1391: Adds transformer engine support and GPU optimizations to T5x (enables H100)
paxml:
  url: https://github.com/google/paxml.git
  mirror_url: https://github.com/nvjax-svc-0/paxml.git
  tracking_ref: main
  latest_verified_commit: 37d5f0ec5768f92574b00dc53169ed267fe465cb
  mode: git-clone
  patches:
    pull/46/head: file://patches/paxml/PR-46.patch # adds Transformer Engine support
    pull/93/head: file://patches/paxml/PR-93.patch # exposes TE DPA argument in Grok to make it configurable from the command line
praxis:
  url: https://github.com/google/praxis.git
  mirror_url: https://github.com/nvjax-svc-0/praxis.git
  tracking_ref: main
  latest_verified_commit: ccd25a1a152c08e6b2d4692bdb640ec6d28d7d9f
  mode: git-clone
  patches:
    pull/27/head: file://patches/praxis/PR-27.patch # This PR allows XLA:GPU to detect the MHA pattern more easily to call fused kernels from cublas.
    pull/36/head: file://patches/praxis/PR-36.patch # adds Transformer Engine support
    pull/84/head: file://patches/praxis/PR-84.patch # experimental support for using TE FMHA in GQA
lingvo:
  # Used only in ARM pax builds
  url: https://github.com/tensorflow/lingvo.git
  tracking_ref: master
  latest_verified_commit: 03fd809d63f852816912cbf28ee299f6a47dbd0b
  mode: git-clone
tensorflow-text:
  # Used only in ARM pax and t5x builds
  url: https://github.com/tensorflow/text.git
  tracking_ref: v2.13.0
  latest_verified_commit: 917a681d7220ebf9b62a08b6f9ce7b7db886ddef
  mode: git-clone
pydantic:
  version: X.Y.Z
  mode: pip-constraint
# Used by praxis
fiddle:
  url: https://github.com/google/fiddle.git
  tracking_ref: main
  latest_verified_commit: d45d7cae1a2d117deb8ee9c2f34e4ba7820d34f0
  mode: pip-vcs
# Used by t5x
airio:
  url: https://github.com/google/airio.git
  tracking_ref: main
  latest_verified_commit: 37109ff0d1059f885b9b11ef9058eca5d219d7cb
  mode: pip-vcs
clu:
  url: https://github.com/google/CommonLoopUtils.git
  tracking_ref: main
  latest_verified_commit: a8152eb825dc04df8acdbb2b42fc89f9aafa37ba
  mode: pip-vcs
dllogger:
  url: https://github.com/NVIDIA/dllogger.git
  tracking_ref: master
  latest_verified_commit: 0540a43971f4a8a16693a9de9de73c1072020769
  mode: pip-vcs
jestimator:
  url: https://github.com/google-research/jestimator.git
  tracking_ref: main
  latest_verified_commit: 326824a477feef6d92e6f44175000907a72899ca
  mode: pip-vcs
optax:
  url: https://github.com/google-deepmind/optax.git
  tracking_ref: main
  latest_verified_commit: 9b682abdadf679113389d5bc21cfb92f87f1463c
  mode: pip-vcs
seqio:
  url: https://github.com/google/seqio.git
  tracking_ref: main
  latest_verified_commit: f9b84ed48e53aa99c16faa00d97b91cd153a6bbb
  mode: pip-vcs
jax-triton:
  url: https://github.com/jax-ml/jax-triton.git
  tracking_ref: main
  latest_verified_commit: 5ddabf37e48d1fecb2470d8351aa19a6c5d8dcf0
  mode: git-clone
maxtext:
  url: https://github.com/google/maxtext.git
  tracking_ref: main
  latest_verified_commit: 3c0be9c331b1833238f5ec307c2c0951ff8b1697
  mode: git-clone
levanter:
  url: https://github.com/stanford-crfm/levanter.git
  tracking_ref: main
  latest_verified_commit: 83f3f34640122476e4fd3955d66b603c82d1e1e3
  mode: git-clone
haliax:
  url: https://github.com/stanford-crfm/haliax.git
  tracking_ref: main
  latest_verified_commit: df27a8d1cd8f4e6f8a988c1ce3e9ae1d8ee122cc
  mode: git-clone
mujoco:
  url: https://github.com/google-deepmind/mujoco.git
  tracking_ref: main
  latest_verified_commit: 7efaf5c549358460f924a6c446c0282bd6b93c63
  mode: git-clone
mujoco-mpc:
  url: https://github.com/google-deepmind/mujoco_mpc.git
  tracking_ref: main
  latest_verified_commit: 9bd2037498056a0ab9cf9463ab841e40fef54142
  mode: git-clone
language-to-reward-2023:
  url: https://github.com/google-deepmind/language_to_reward_2023.git
  tracking_ref: main
  latest_verified_commit: 4a3a20f9c8705e3a3ded4d218d9c129303d9682e
  mode: git-clone
mlperf-logging:
  url: https://github.com/mlcommons/logging.git
  tracking_ref: master
  latest_verified_commit: b81c2116986fe108fa2267c9052c249149fe6717
  mode: pip-vcs
gemma:
  url: https://github.com/google-deepmind/gemma.git
  tracking_ref: main
  latest_verified_commit: b1db0176dac293167b02bd00fdd24ddfa04b2879
  mode: git-clone
equinox:
  url: https://github.com/patrick-kidger/equinox.git
  tracking_ref: main
  latest_verified_commit: 1b507b9dfcc6a3a65470dbaa8c4be6c0a0e2a16a
  mode: git-clone
big-vision:
  url: https://github.com/google-research/big_vision.git
  tracking_ref: main
  latest_verified_commit: 451b66357124949bf215c926d2fdf110f58274d0
  mode: git-clone
common-loop-utils:
  url: https://github.com/google/CommonLoopUtils.git
  tracking_ref: main
  latest_verified_commit: a8152eb825dc04df8acdbb2b42fc89f9aafa37ba
  mode: git-clone
flaxformer:
  url: https://github.com/google/flaxformer.git
  tracking_ref: main
  latest_verified_commit: 399ea3a85e9807ada653fd0de1a9de627eb0acde
  mode: git-clone
panopticapi:
  url: https://github.com/akolesnikoff/panopticapi.git
  tracking_ref: mute
  latest_verified_commit: a698a12deb21e4cf0f99ef0581b2c30c466bf355
  mode: git-clone
orbax-checkpoint:
  url: https://github.com/google/orbax.git
  tracking_ref: main
  latest_verified_commit: 69a1fcb560d7b67eaf5ae70d769efdd3a972ef62
  mode: pip-vcs
pathwaysutils:
  url: https://github.com/google/pathways-utils.git
  tracking_ref: main
  latest_verified_commit: c236218e6c249016468b4f7308a60f5f96849033
  mode: pip-vcs
